name: version_banner
description: A banner that shows the current version or flavour of the app
version: 0.2.1
homepage: https://github.com/Vanethos/flutter_version_banner
issue_tracker: https://github.com/Vanethos/flutter_version_banner/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info: '2.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: